{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "happypath.fullname" . }}-minio
  labels:
    {{- include "happypath.labels" . | nindent 4 }}
    {{- include "happypath.minio.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "happypath.minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "happypath.minio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          command:
            - minio
            - server
            - /data
            - "--console-address"
            - ":9001"
          ports:
            - containerPort: {{ .Values.minio.service.apiPort }}
              name: s3-api
            - containerPort: {{ .Values.minio.service.consolePort }}
              name: console
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: happypath-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: happypath-secrets
                  key: MINIO_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: {{ .Values.minio.service.apiPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: {{ .Values.minio.service.apiPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          {{- if .Values.minio.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "happypath.fullname" . }}-minio-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
